# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Project.create([
  { name: "Accor" },
  { name: "Admin" },
  { name: "Alliants-Bus Ops" },
  { name: "Alliants-Compassionate Leave" },
  { name: "Alliants-Finance" },
  { name: "Alliants-ill" },
  { name: "Alliants-investment" },
  { name: "Alliants-leave" },
  { name: "Alliants-meetings" },
  { name: "Alliants-Public Leave" },
  { name: "Alliants-review" },
  { name: "Alliants-training" },
  { name: "Alliants-upaid leave" },
  { name: "Babylon" },
  { name: "babylon - support" },
  { name: "babylon-mercer" },
  { name: "babylon-react" },
  { name: "BD-FS-Booking-API" },
  { name: "Business Development" },
  { name: "chat-prototype" },
  { name: "EEA Grants Bid" },
  { name: "Finance" },
  { name: "Forrest" },
  { name: "Fredericks-bd" },
  { name: "FS Italy Promotion" },
  { name: "FS Test & Implement" },
  { name: "FS-BD-Geolocation" },
  { name: "FS-BD-Packages" },
  { name: "FS-Brand Review" },
  { name: "FS-Checkin Contest" },
  { name: "FS-Flybits" },
  { name: "FS-Guest Center" },
  { name: "FS-Lanai Activities" },
  { name: "FS-Lemonade" },
  { name: "FS-Marketing" },
  { name: "FS-Mob" },
  { name: "FS-Mobile Accommodations" },
  { name: "FS-Mobile Api" },
  { name: "FS-Mobile Chat" },
  { name: "FS-Mobile Residential" },
  { name: "FS-Nuggets" },
  { name: "FS-Owner Portal" },
  { name: "FS-Palm Beach" },
  { name: "FS-PCTSydney" },
  { name: "FS-Raygun" },
  { name: "FS-Res" },
  { name: "fs-sso" },
  { name: "FS-Step2" },
  { name: "FS-Web Maintenance" },
  { name: "GE-ehc" },
  { name: "GE-RAY" },
  { name: "Gov Framework" },
  { name: "GSW-Res" },
  { name: "hoozzi" },
  { name: "Hub" },
  { name: "Incisively" },
  { name: "Itchen Imperial" },
  { name: "Marketing and branding" },
  { name: "Menu-via-Message" },
  { name: "Messenger app" },
  { name: "Noths" },
  { name: "racing" },
  { name: "RIFT Forms" },
  { name: "RIFT maintenence" },
  { name: "RIFT Workflow" },
  { name: "Samsung" },
  { name: "Samsung 2017 Budget Definitions" },
  { name: "Samsung Members Data Migration" },
  { name: "Samsung Members for Dream launch" },
  { name: "SMYKM" },
  { name: "Travel" },
  { name: "Triptease" },
  { name: "Visit Britain" }
])
