Project.create([
  { name: "Accor" },
  { name: "Admin" },
  { name: "Alliants-Branding" },
  { name: "Alliants-Bus Ops" },
  { name: "Alliants-Christmas Party" },
  { name: "Alliants-Compassionate Leave" },
  { name: "Alliants-Finance" },
  { name: "Alliants-ill" },
  { name: "Alliants-investment" },
  { name: "Alliants-leave" },
  { name: "Alliants-meetings" },
  { name: "Alliants-party" },
  { name: "Alliants-Public Leave" },
  { name: "Alliants-training" },
  { name: "Alliants-upaid leave" },
  { name: "babylon - support" },
  { name: "babylon-mercer" },
  { name: "babylon-react" },
  { name: "BD-Babylon" },
  { name: "BD-Butterfly" },
  { name: "BD-Elevate" },
  { name: "BD-Fourseasons" },
  { name: "BD-Fredericks" },
  { name: "BD-FS-Booking-API" },
  { name: "BD-General" },
  { name: "BD-RIFT" },
  { name: "BD-ROH" },
  { name: "BD-TreasureKnit" },
  { name: "BD-Triptease" },
  { name: "Butterfly" },
  { name: "Dancing like in flashdance" },
  { name: "Dnata-Review" },
  { name: "EEA Grants Bid" },
  { name: "Elevate-iYield" },
  { name: "Finance" },
  { name: "Forrest" },
  { name: "FS Italy Promotion" },
  { name: "FS-BD-Geolocation" },
  { name: "FS-BD-Packages" },
  { name: "FS-Brand Review" },
  { name: "FS-Checkin Contest" },
  { name: "FS-Exclusive Offers Phase 1" },
  { name: "FS-Flybits" },
  { name: "FS-Guest Center" },
  { name: "FS-Lanai Activities" },
  { name: "FS-Lanai Calendar" },
  { name: "FS-Lemonade" },
  { name: "FS-Marketing" },
  { name: "FS-Mob" },
  { name: "FS-Mobile Accommodations" },
  { name: "FS-Mobile Api" },
  { name: "FS-Mobile Chat" },
  { name: "FS-Mobile Maintenance" },
  { name: "FS-Mobile Residential" },
  { name: "FS-New York Midtown" },
  { name: "FS-Nomi" },
  { name: "FS-Nuggets" },
  { name: "FS-Owner Portal" },
  { name: "FS-Palm Beach" },
  { name: "FS-PCTSydney" },
  { name: "FS-Pre-Arrival" },
  { name: "FS-Raygun" },
  { name: "FS-Res" },
  { name: "fs-sso" },
  { name: "FS-Step2" },
  { name: "FS-Test &amp; Implement" },
  { name: "FS-Test and Implement 2017" },
  { name: "FS-Web Maintenance" },
  { name: "GE-ehc" },
  { name: "ge-hef" },
  { name: "GE-RAY" },
  { name: "GE-SCF" },
  { name: "Gov Framework" },
  { name: "GSW-Res" },
  { name: "GyniiMi" },
  { name: "HF-Test" },
  { name: "hoozzi" },
  { name: "Hub" },
  { name: "Incisively" },
  { name: "Itchen Imperial" },
  { name: "iYield Phase 2" },
  { name: "log yesterday" },
  { name: "Menu-via-Message" },
  { name: "Messenger app" },
  { name: "Noths" },
  { name: "racing" },
  { name: "Rift - Maintenance" },
  { name: "RIFT Workflow" },
  { name: "ROH" },
  { name: "Samsung" },
  { name: "Samsung 2017 Budget Definitions" },
  { name: "samsung members" },
  { name: "samsung members 2017" },
  { name: "Samsung Members Extension" },
  { name: "Samsung Members for Dream launch" },
  { name: "Sas" },
  { name: "SMYKM" },
  { name: "Travel" },
  { name: "Travelport" },
  { name: "Triptease" },
  { name: "VB-Discovery" },
  { name: "Visit Britain" },
  { name: "yes" },
])
